// ─────────────────────────────────────────────────────────────────────────────
// Alias databases for team & market normalization
// In production these are populated from the DB (fixture_aliases / market_aliases).
// ─────────────────────────────────────────────────────────────────────────────

export const TEAM_ALIASES: Record<string, string> = {
  // Manchester United
  'manchester utd': 'Manchester United',
  'man united': 'Manchester United',
  'man utd': 'Manchester United',
  'manchester united fc': 'Manchester United',
  'manchester united': 'Manchester United',
  'mu fc': 'Manchester United',
  'mufc': 'Manchester United',
  'red devils': 'Manchester United',
  // Manchester City
  'manchester city': 'Manchester City',
  'man city': 'Manchester City',
  'manchester city fc': 'Manchester City',
  'mancity': 'Manchester City',
  'mcfc': 'Manchester City',
  'citizens': 'Manchester City',
  // Chelsea
  'chelsea': 'Chelsea',
  'chelsea fc': 'Chelsea',
  'the blues': 'Chelsea',
  'cfc': 'Chelsea',
  // Arsenal
  'arsenal': 'Arsenal',
  'arsenal fc': 'Arsenal',
  'gunners': 'Arsenal',
  'afc': 'Arsenal',
  // Liverpool
  'liverpool': 'Liverpool',
  'liverpool fc': 'Liverpool',
  'lfc': 'Liverpool',
  'reds': 'Liverpool',
  // Tottenham
  'tottenham': 'Tottenham Hotspur',
  'spurs': 'Tottenham Hotspur',
  'tottenham hotspur': 'Tottenham Hotspur',
  'thfc': 'Tottenham Hotspur',
  // Leicester
  'leicester': 'Leicester City',
  'leicester city': 'Leicester City',
  'foxes': 'Leicester City',
  'lcfc': 'Leicester City',
  // West Ham
  'west ham': 'West Ham United',
  'west ham united': 'West Ham United',
  'west ham fc': 'West Ham United',
  'hammers': 'West Ham United',
  'whu': 'West Ham United',
  // Everton
  'everton': 'Everton',
  'everton fc': 'Everton',
  'toffees': 'Everton',
  // Aston Villa
  'aston villa': 'Aston Villa',
  'villa': 'Aston Villa',
  'avfc': 'Aston Villa',
  // Newcastle
  'newcastle': 'Newcastle United',
  'newcastle united': 'Newcastle United',
  'nufc': 'Newcastle United',
  'magpies': 'Newcastle United',
  // Leeds
  'leeds': 'Leeds United',
  'leeds united': 'Leeds United',
  'lufc': 'Leeds United',
  // Wolverhampton
  'wolves': 'Wolverhampton Wanderers',
  'wolverhampton': 'Wolverhampton Wanderers',
  'wolverhampton wanderers': 'Wolverhampton Wanderers',
  'wwfc': 'Wolverhampton Wanderers',
  // Brighton
  'brighton': 'Brighton & Hove Albion',
  'brighton hove albion': 'Brighton & Hove Albion',
  'brighton & hove albion': 'Brighton & Hove Albion',
  'seagulls': 'Brighton & Hove Albion',
  // Brentford
  'brentford': 'Brentford',
  'brentford fc': 'Brentford',
  'bees': 'Brentford',
  // Fulham
  'fulham': 'Fulham',
  'fulham fc': 'Fulham',
  'cottagers': 'Fulham',
  // Crystal Palace
  'crystal palace': 'Crystal Palace',
  'palace': 'Crystal Palace',
  'eagles': 'Crystal Palace',
  // Nottingham Forest
  'nottingham forest': 'Nottingham Forest',
  'forest': 'Nottingham Forest',
  'nottm forest': 'Nottingham Forest',
  'nffc': 'Nottingham Forest',
  // Bournemouth
  'bournemouth': 'Bournemouth',
  'afcb': 'Bournemouth',
  'cherries': 'Bournemouth',
  // Southampton
  'southampton': 'Southampton',
  'saints': 'Southampton',
  'sfc': 'Southampton',
  // Norwich
  'norwich': 'Norwich City',
  'norwich city': 'Norwich City',
  'canaries': 'Norwich City',
  // Watford
  'watford': 'Watford',
  'hornets': 'Watford',
  // Burnley
  'burnley': 'Burnley',
  'clarets': 'Burnley',
  // Sheffield United
  'sheffield united': 'Sheffield United',
  'sheffield utd': 'Sheffield United',
  'blades': 'Sheffield United',
  // Luton Town
  'luton': 'Luton Town',
  'luton town': 'Luton Town',
  'hatters': 'Luton Town',
  // ── Spanish ──
  'real madrid': 'Real Madrid',
  'barcelona': 'FC Barcelona',
  'fc barcelona': 'FC Barcelona',
  'barca': 'FC Barcelona',
  'atletico madrid': 'Atlético Madrid',
  'atletico': 'Atlético Madrid',
  'athletico madrid': 'Atlético Madrid',
  'sevilla': 'Sevilla',
  'valencia': 'Valencia',
  'villarreal': 'Villarreal',
  'real sociedad': 'Real Sociedad',
  'real betis': 'Real Betis',
  'athletic bilbao': 'Athletic Bilbao',
  'athletic club': 'Athletic Bilbao',
  // ── Italian ──
  'juventus': 'Juventus',
  'inter': 'Inter Milan',
  'inter milan': 'Inter Milan',
  'ac milan': 'AC Milan',
  'milan': 'AC Milan',
  'napoli': 'Napoli',
  'roma': 'AS Roma',
  'as roma': 'AS Roma',
  'lazio': 'Lazio',
  'atalanta': 'Atalanta',
  'fiorentina': 'Fiorentina',
  'torino': 'Torino',
  'bologna': 'Bologna',
  // ── German ──
  'bayern munich': 'Bayern Munich',
  'bayern': 'Bayern Munich',
  'borussia dortmund': 'Borussia Dortmund',
  'dortmund': 'Borussia Dortmund',
  'bvb': 'Borussia Dortmund',
  'rb leipzig': 'RB Leipzig',
  'leverkusen': 'Bayer Leverkusen',
  'bayer leverkusen': 'Bayer Leverkusen',
  'frankfurt': 'Eintracht Frankfurt',
  'wolfsburg': 'VfL Wolfsburg',
  'monchengladbach': 'Borussia Mönchengladbach',
  'borussia monchengladbach': 'Borussia Mönchengladbach',
  'union berlin': 'Union Berlin',
  'freiburg': 'SC Freiburg',
  'hoffenheim': 'TSG Hoffenheim',
  'stuttgart': 'VfB Stuttgart',
  // ── French ──
  'psg': 'Paris Saint-Germain',
  'paris saint germain': 'Paris Saint-Germain',
  'paris saint-germain': 'Paris Saint-Germain',
  'marseille': 'Olympique Marseille',
  'om': 'Olympique Marseille',
  'lyon': 'Olympique Lyonnais',
  'ol': 'Olympique Lyonnais',
  'monaco': 'AS Monaco',
  'lille': 'Lille',
  'nice': 'Nice',
  'rennes': 'Rennes',
  'nantes': 'Nantes',
  'lens': 'Lens',
  // ── Nigerian ──
  'enugu rangers': 'Enugu Rangers',
  'rangers intl': 'Enugu Rangers',
  'rangers international': 'Enugu Rangers',
  'shooting stars': 'Shooting Stars',
  '3sc': 'Shooting Stars',
  'enyimba': 'Enyimba FC',
  'enyimba fc': 'Enyimba FC',
  'kano pillars': 'Kano Pillars',
  'rivers united': 'Rivers United',
  'plateau united': 'Plateau United',
  'sunshine stars': 'Sunshine Stars',
  'kwara united': 'Kwara United',
  'lokomotiv': 'Lokomotiv',
  'akwa united': 'Akwa United',
  'nasarawa united': 'Nasarawa United',
  'el kanemi warriors': 'El Kanemi Warriors',
  'bendel insurance': 'Bendel Insurance',
  'heartland': 'Heartland FC',
  'abia warriors': 'Abia Warriors',
  'gombe united': 'Gombe United',
  'dolphins': 'Dolphins FC',
  'ifeanyiubah': 'FC Ifeanyiubah',
  'lobi stars': 'Lobi Stars',
  'wikki tourist': 'Wikki Tourist',
  // ── Other European ──
  'ajax': 'AFC Ajax',
  'afc ajax': 'AFC Ajax',
  'psv': 'PSV Eindhoven',
  'psv eindhoven': 'PSV Eindhoven',
  'feyenoord': 'Feyenoord',
  'porto': 'FC Porto',
  'fc porto': 'FC Porto',
  'benfica': 'Benfica',
  'sporting': 'Sporting CP',
  'sporting cp': 'Sporting CP',
  'braga': 'SC Braga',
  'celtic': 'Celtic',
  'rangers fc': 'Rangers',
  'rangers': 'Rangers',
  'celtic fc': 'Celtic',
};

export const MARKET_ALIASES: Record<string, string> = {
  // 1X2 / Match Winner
  '1x2': 'Match Winner (1X2)',
  'match winner': 'Match Winner (1X2)',
  'match result': 'Match Winner (1X2)',
  'full time result': 'Match Winner (1X2)',
  'fulltime result': 'Match Winner (1X2)',
  'ft result': 'Match Winner (1X2)',
  'result': 'Match Winner (1X2)',
  'home/draw/away': 'Match Winner (1X2)',
  'w1x2': 'Match Winner (1X2)',
  '1x2 (fulltime)': 'Match Winner (1X2)',
  'home win': 'Match Winner (1X2)',
  'away win': 'Match Winner (1X2)',
  'draw': 'Match Winner (1X2)',
  // Double Chance
  'double chance': 'Double Chance',
  'dc': 'Double Chance',
  '1x': 'Double Chance',
  'x2': 'Double Chance',
  '12': 'Double Chance',
  'double chance (1x2)': 'Double Chance',
  // Over/Under Goals
  'over/under': 'Over/Under Goals',
  'over/under goals': 'Over/Under Goals',
  'over under': 'Over/Under Goals',
  'total goals': 'Over/Under Goals',
  'goals over/under': 'Over/Under Goals',
  'ou': 'Over/Under Goals',
  'o/u': 'Over/Under Goals',
  'over/under 2.5': 'Over/Under Goals',
  'over 2.5': 'Over/Under Goals',
  'under 2.5': 'Over/Under Goals',
  // Both Teams to Score
  'btts': 'Both Teams to Score',
  'both teams to score': 'Both Teams to Score',
  'bts': 'Both Teams to Score',
  'gg': 'Both Teams to Score',
  'goal goal': 'Both Teams to Score',
  'ng': 'Both Teams to Score',
  'no goal': 'Both Teams to Score',
  // Handicap
  'handicap': 'Asian Handicap',
  'asian handicap': 'Asian Handicap',
  'ah': 'Asian Handicap',
  'hcp': 'Asian Handicap',
  '1x2 handicap': 'Asian Handicap',
  // Draw No Bet
  'draw no bet': 'Draw No Bet',
  'dnb': 'Draw No Bet',
  // Correct Score
  'correct score': 'Correct Score',
  'cs': 'Correct Score',
  // Half Time Result
  'half time result': 'Half Time Result',
  'ht result': 'Half Time Result',
  '1st half result': 'Half Time Result',
  'half time 1x2': 'Half Time Result',
  // Half Time/Full Time
  'ht/ft': 'Half Time/Full Time',
  'htft': 'Half Time/Full Time',
  'half time/full time': 'Half Time/Full Time',
  // Over/Under Corners
  'corners over/under': 'Corners Over/Under',
  'corner ou': 'Corners Over/Under',
  // Cards
  'cards over/under': 'Cards Over/Under',
  'booking points': 'Cards Over/Under',
  // Anytime Goalscorer
  'anytime goalscorer': 'Anytime Goalscorer',
  'ags': 'Anytime Goalscorer',
  // First Goalscorer
  'first goalscorer': 'First Goalscorer',
  'fgs': 'First Goalscorer',
  // To Win to Nil
  'win to nil': 'To Win to Nil',
  'wtn': 'To Win to Nil',
  // Total Goals (exact)
  'total goals exact': 'Total Goals (Exact)',
  'exact goals': 'Total Goals (Exact)',
};

export const SELECTION_ALIASES: Record<string, string> = {
  '1': 'Home Win',
  'home': 'Home Win',
  'w1': 'Home Win',
  'home win': 'Home Win',
  '2': 'Away Win',
  'away': 'Away Win',
  'w2': 'Away Win',
  'away win': 'Away Win',
  'x': 'Draw',
  'draw': 'Draw',
  // Double chance selections
  '1x': 'Home or Draw',
  'home or draw': 'Home or Draw',
  'home/draw': 'Home or Draw',
  'x2': 'Draw or Away',
  'draw or away': 'Draw or Away',
  'draw/away': 'Draw or Away',
  '12': 'Home or Away',
  'home or away': 'Home or Away',
  'home/away': 'Home or Away',
  // Over/Under
  'over': 'Over',
  'over 2.5': 'Over 2.5',
  'under': 'Under',
  'under 2.5': 'Under 2.5',
  'o2.5': 'Over 2.5',
  'u2.5': 'Under 2.5',
  // BTTS
  'yes': 'Yes',
  'no': 'No',
  'gg': 'Yes',
  'ng': 'No',
};
