import type { Bookmaker, BookmakerId } from './types';

export const BOOKMAKERS: Record<BookmakerId, Bookmaker> = {
  bet9ja: {
    id: 'bet9ja',
    name: 'Bet9ja',
    shortName: 'B9',
    color: '#00a651',
    website: 'https://bet9ja.com',
    logoUrl: '/logos/bet9ja.svg',
    active: true,
    integrationMode: 'simulated',
  },
  sportybet: {
    id: 'sportybet',
    name: 'SportyBet',
    shortName: 'SB',
    color: '#0b9d00',
    website: 'https://sportybet.com',
    logoUrl: '/logos/sportybet.svg',
    active: true,
    integrationMode: 'live',
  },
  betking: {
    id: 'betking',
    name: 'BetKing',
    shortName: 'BK',
    color: '#f5a623',
    website: 'https://betking.com',
    logoUrl: '/logos/betking.svg',
    active: true,
    integrationMode: 'simulated',
  },
  '1xbet': {
    id: '1xbet',
    name: '1xBet',
    shortName: '1X',
    color: '#0a6cff',
    website: 'https://1xbet.ng',
    logoUrl: '/logos/1xbet.svg',
    active: true,
    integrationMode: 'simulated',
  },
  nairabet: {
    id: 'nairabet',
    name: 'NairaBet',
    shortName: 'NB',
    color: '#1a73e8',
    website: 'https://nairabet.com',
    logoUrl: '/logos/nairabet.svg',
    active: true,
    integrationMode: 'simulated',
  },
  merrybet: {
    id: 'merrybet',
    name: 'MerryBet',
    shortName: 'MB',
    color: '#d4af37',
    website: 'https://merrybet.com',
    logoUrl: '/logos/merrybet.svg',
    active: true,
    integrationMode: 'simulated',
  },
  bangbet: {
    id: 'bangbet',
    name: 'BangBet',
    shortName: 'BB',
    color: '#e6007e',
    website: 'https://bangbet.com',
    logoUrl: '/logos/bangbet.svg',
    active: true,
    integrationMode: 'simulated',
  },
  msport: {
    id: 'msport',
    name: 'MSport',
    shortName: 'MS',
    color: '#7b2ff7',
    website: 'https://msport.com',
    logoUrl: '/logos/msport.svg',
    active: true,
    integrationMode: 'simulated',
  },
  surebet247: {
    id: 'surebet247',
    name: 'SureBet247',
    shortName: 'S247',
    color: '#ff6b00',
    website: 'https://surebet247.com',
    logoUrl: '/logos/surebet247.svg',
    active: true,
    integrationMode: 'simulated',
  },
  premierbet: {
    id: 'premierbet',
    name: 'Premier Bet',
    shortName: 'PB',
    color: '#c8102e',
    website: 'https://premierbet.com',
    logoUrl: '/logos/premierbet.svg',
    active: true,
    integrationMode: 'simulated',
  },
  bet365: {
    id: 'bet365',
    name: 'Bet365',
    shortName: 'B365',
    color: '#0f6d3f',
    website: 'https://www.bet365.com',
    logoUrl: '/logos/bet365.svg',
    active: true,
    integrationMode: 'simulated',
  },
  williamhill: {
    id: 'williamhill',
    name: 'William Hill',
    shortName: 'WH',
    color: '#0a2f7a',
    website: 'https://www.williamhill.com',
    logoUrl: '/logos/williamhill.svg',
    active: true,
    integrationMode: 'simulated',
  },
  ladbrokes: {
    id: 'ladbrokes',
    name: 'Ladbrokes',
    shortName: 'LB',
    color: '#e30613',
    website: 'https://www.ladbrokes.com',
    logoUrl: '/logos/ladbrokes.svg',
    active: true,
    integrationMode: 'simulated',
  },
  coral: {
    id: 'coral',
    name: 'Coral',
    shortName: 'CR',
    color: '#0066cc',
    website: 'https://www.coral.co.uk',
    logoUrl: '/logos/coral.svg',
    active: true,
    integrationMode: 'simulated',
  },
  paddypower: {
    id: 'paddypower',
    name: 'Paddy Power',
    shortName: 'PP',
    color: '#00a85a',
    website: 'https://www.paddypower.com',
    logoUrl: '/logos/paddypower.svg',
    active: true,
    integrationMode: 'simulated',
  },
  skybet: {
    id: 'skybet',
    name: 'Sky Bet',
    shortName: 'SKY',
    color: '#0033a0',
    website: 'https://www.skybet.com',
    logoUrl: '/logos/skybet.svg',
    active: true,
    integrationMode: 'simulated',
  },
  betfair: {
    id: 'betfair',
    name: 'Betfair',
    shortName: 'BF',
    color: '#ffb81c',
    website: 'https://www.betfair.com',
    logoUrl: '/logos/betfair.svg',
    active: true,
    integrationMode: 'simulated',
  },
  betvictor: {
    id: 'betvictor',
    name: 'BetVictor',
    shortName: 'BV',
    color: '#1f4aa8',
    website: 'https://www.betvictor.com',
    logoUrl: '/logos/betvictor.svg',
    active: true,
    integrationMode: 'simulated',
  },
  unibet: {
    id: 'unibet',
    name: 'Unibet',
    shortName: 'UNI',
    color: '#00843d',
    website: 'https://www.unibet.co.uk',
    logoUrl: '/logos/unibet.svg',
    active: true,
    integrationMode: 'simulated',
  },
  '888sport': {
    id: '888sport',
    name: '888sport',
    shortName: '888',
    color: '#111111',
    website: 'https://www.888sport.com',
    logoUrl: '/logos/888sport.svg',
    active: true,
    integrationMode: 'simulated',
  },
};

export const BOOKMAKER_LIST = Object.values(BOOKMAKERS);

export function getBookmaker(id: BookmakerId): Bookmaker {
  return BOOKMAKERS[id];
}

export function getIntegrationModeLabel(id: BookmakerId): string {
  return BOOKMAKERS[id].integrationMode === 'live' ? 'Live API' : 'Simulated';
}

export function isBookmakerLive(id: BookmakerId): boolean {
  return BOOKMAKERS[id].integrationMode === 'live';
}
